name: Update Workflow

on:
  push:
    branches:
      - main

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      
      - name: Run Automate
        run: python tools/automate.py

      - name: List files in workflows directory
        run: ls -la .github/workflows/

      - name: Configure Git
        run: |
          git config --global user.name "budhi-halim"
          git config --global user.email "halimbudhiarto@gmail.com"

      - name: Verify Git Status Before add
        run: git status

      - name: Add Files to Git
        run: git add -v .github/workflows/execute_scripts.yml

      - name: Verify Git Status After add
        run: git status

      - name: Commit changes
        run: |
          git commit -m "Update Workflow" || echo "No Changes to Commit"

      - name: Push changes
        run: git push https://x-access-token:${{ secrets.PAT_TOKEN_REPO }}@github.com/budhi-halim/update.git