name: Update Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  workflows: write

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.13.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      
      - name: Run Automate
        run: python tools/automate.py

      - name: Add files to Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/execute_scripts.yml

      - name: Commit changes
        run: |
          git commit -m "Update Workflow" || echo "No Changes to Commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}