name: Update Workflow

on:
  push:
    branches:
      - main

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.0

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
      
      - name: Run Automate
        run: python tools/automate.py

      - name: List files in workflows directory
        run: ls -la .github/workflows/

      - name: Add files to Git
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git add .github/workflows/execute_scripts.yml

      - name: Commit changes
        run: |
          git commit -m "Update Workflow" || echo "No Changes to Commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_REPO }}
        run: |
          git push https://$PAT_TOKEN@github.com/$GITHUB_REPOSITORY HEAD:main || echo "Push failed"